version: '3.5'
services:
  couchbase1:
    container_name: couchbase1
    image: couchbase:enterprise-7.1.3
    volumes:
    - type: volume
      source: couchbase1
      target: /opt/couchbase/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.13
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    ulimits:
      nproc: 65535
      core:
        soft: 100000000
        hard: 100000000
      memlock:
        soft: 100000000
        hard: 100000000
      nofile:
        soft: 40960
        hard: 40960
  couchbase2:
    container_name: couchbase2
    image: couchbase:enterprise-7.1.3
    volumes:
    - type: volume
      source: couchbase2
      target: /opt/couchbase/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.14
    links:
      - couchbase1
    depends_on:
      - couchbase1
    ports:
      - 48091:8091
      - 48092:8092
      - 48093:8093
      - 48094:8094
      - 41210:11210
    ulimits:
      nproc: 65535
      core:
        soft: 100000000
        hard: 100000000
      memlock:
        soft: 100000000
        hard: 100000000
      nofile:
        soft: 40960
        hard: 40960
networks:
  couchbase-net:
    name: couchbase-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.101.0/24
volumes:
  couchbase1:
  couchbase2: