# RUN THIS COMMAND BEFORE RUNNING docker-compose up -d
# docker network create --gateway 172.18.1.1 --subnet 172.18.1.0/24 app_net
version: "3.9"
services:
  master:
    image: mouadmem16/openssh-alpine:v0.1-python
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.18.1.3

  worker1:
    image: mouadmem16/openssh-alpine:v0.1-python
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.18.1.4

  worker2:
    image: mouadmem16/openssh-alpine:v0.1-python
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.18.1.5

  worker3:
    image: mouadmem16/openssh-alpine:v0.1-python
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.18.1.6

networks:
  app_net:
   external: true
